package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.RestClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.testng.annotations.Test;

public class CustomersTest {
    private AccountTokenPojo adminToken;
    private CustomerPojo customerPojo;

    @Test(description = "Create customer.")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Customers feature.")
    public void createCustomerTest() {
        adminToken = new RestClient().authenticate("admin", "setup");

        customerPojo = new RestClient().createAutoGeneratedCustomer(adminToken);

        new RestClient().createCustomer(customerPojo, adminToken);
    }

    @Test(description = "Delete customer.", dependsOnMethods = "createCustomerTest")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Customers feature.")
    public void deleteCustomerTest() {

        new RestClient().deleteCustomer(customerPojo, adminToken);

    }
}
