package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.RestClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.testng.annotations.Test;

public class MeTest {
    private AccountTokenPojo adminToken;

    @Test(description = "Get my personal info for admin.")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Get personal info feature.")
    public void getPersonalInfoAdminTest() {
        adminToken = new RestClient().authenticate("admin", "setup");

        new RestClient().getMyPersonalInfo(adminToken);
    }

    @Test(description = "Get my personal info for customer.", dependsOnMethods = "getPersonalInfoAdminTest")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Get personal info feature.")
    public void getPersonalInfoCustomerTest() {
        RestClient restClient = new RestClient();
        CustomerPojo customerPojo = restClient.createAutoGeneratedCustomer(adminToken);

        AccountTokenPojo customerToken = restClient.authenticate(customerPojo.login, customerPojo.password);

        restClient.getMyPersonalInfo(customerToken);
    }

}
