package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.RestClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.testng.annotations.Test;

public class TopUpBalanceTest {

    @Test(description = "Create customer.")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Customers feature.")
    public void createCustomerTest() {
        RestClient restClient = new RestClient();
        AccountTokenPojo adminToken = restClient.authenticate("admin", "setup");

        CustomerPojo customerPojo = restClient.createAutoGeneratedCustomer(adminToken);

        AccountTokenPojo authenticate = restClient.authenticate(customerPojo.login, customerPojo.password);

        restClient.topUpBalanceCustomer(customerPojo, 10, authenticate);
    }

}
